"""
Django settings for FutureCode0901 project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=3tbg5@vel&anga)y^u&p%s$9s609ootj$ix8e8obn1_e5-#a9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
    'magazine',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FutureCode0901.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FutureCode0901.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'NAME': 'futurecode0901',
        'USER': 'postgres',
        'PASSWORD': 'simosa'

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# URL-адрес внутри сервера, для обращения к файлам
# По умолчанию
STATIC_URL = 'static/'

# Местоположение сохранения медиа файлов (внутри проекта в папке files)
# К путям FileField, ImageField в начале добавляется MEDIA_ROOT
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Список путей статичных файлах, которые находятся в необычных местах.
# (Статика автоматически ищется по папкам static в приложениях)
STATICFILES_DIRS = [
    BASE_DIR / 'FutureCode0901/static'
]

# python manage.py collectstatic - Собирает статику в один файл (по пути STATIC_ROOT)
# по большей части данная команда нужна для вывода проекта на продакшен, т.к.
# При DEBUG = True - статика берется напрямую из приложения и получается мы не обращаемся по STATIC_ROOT
# При DEBUG = False - статика берется из внешнего источника, а именно из сервера,
# в этом случае проще указать STATIC_ROOT скидывать в папку, где сервер опубликует внутри себя эти стили,
# и ссылаться будем по URL-адресу сервера забирая статику.

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field



# URL-адрес внутри сервера, для обращения к файлам
MEDIA_URL = 'media/'

# Местоположение сохранения медиа файлов (внутри проекта в папке files)
# К путям FileField, ImageField в начале добавляется MEDIA_ROOT
MEDIA_ROOT = os.path.join(BASE_DIR, 'files')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/magazine/login/'