# Generated by Django 5.0 on 2024-01-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametr',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристика'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('change_address', 'Возможность изменить адрес доставки'), ('can_del_supplier', 'Возможность удалить поставщика')], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_exists',
            field=models.BooleanField(default=True, verbose_name='Логическое удаление'),
        ),
    ]
